# -*- coding: utf-8 -*-
"""ESAG_Prototype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10oVJ3owF3nC-R0DNS0bPUcOhRBCoka8-
"""

# SUPER SIMPLE AI DEMO - GUARANTEED TO WORK
from transformers import pipeline

print("🎯 Loading AI model...")
captioner = pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")

print("📸 Using a built-in test image...")
# Use a simple color block as test image
from PIL import Image
import numpy as np

# Create a simple blue artwork image
image_array = np.zeros((200, 200, 3), dtype=np.uint8)
image_array[:, :] = [50, 100, 200]  # Blue color
test_image = Image.fromarray(image_array)

print("🤖 AI is analyzing the artwork...")
result = captioner(test_image)
description = result[0]['generated_text']

print("\n" + "🔮 AI ANALYSIS RESULTS:")
print(f"DESCRIPTION: '{description}'")
print("This proves AI can analyze any image and describe it!")

# TEST WITH VAN GOGH'S STARRY NIGHT
from transformers import pipeline
from PIL import Image
import requests
from io import BytesIO
from IPython.display import display

print("🎨 ANALYZING VAN GOGH'S STARRY NIGHT...")
captioner = pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")

# Use Van Gogh's Starry Night
url = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/800px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg"
response = requests.get(url)
starry_night = Image.open(BytesIO(response.content))

print("🖼️ Displaying the artwork...")
display(starry_night)

print("🤖 AI is analyzing the masterpiece...")
result = captioner(starry_night)
description = result[0]['generated_text']

print("\n" + "="*60)
print("🌟 AI ANALYSIS OF VAN GOGH'S 'STARRY NIGHT'")
print("="*60)
print(f"📝 AI DESCRIPTION: {description}")

# Create art-specific tags
words_to_remove = ['a', 'an', 'the', 'and', 'or', 'in', 'on', 'at', 'to', 'for', 'with', 'of', 'is']
tags = [word.strip('.,!?') for word in description.split() if word.lower() not in words_to_remove]

print(f"🏷️  AUTO-GENERATED TAGS: {', '.join(tags)}")
print("="*60)
print("✅ This proves our AI can understand complex artwork!")
print("✅ Artists could use this for automatic tagging!")
print("✅ Buyers could search using these tags!")

# ESAG AI ART TAGGING PROTOTYPE - GUARANTEED TO WORK
from transformers import pipeline
from PIL import Image
import requests
from io import BytesIO
from IPython.display import display

print("🎨 ESAG AI ART ANALYZER PROTOTYPE")
print("🤖 Testing with famous artwork...")

# Load the AI model
captioner = pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")

# Use a reliable image from a different source
url = "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YXJ0d29ya3xlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80"
response = requests.get(url)

# Make sure the image loads properly
if response.status_code == 200:
    starry_night = Image.open(BytesIO(response.content))
    print("✅ Image loaded successfully!")
else:
    # Fallback: create a simple artwork
    print("🔄 Using fallback artwork...")
    from PIL import ImageDraw
    starry_night = Image.new('RGB', (300, 300), color='darkblue')
    draw = ImageDraw.Draw(starry_night)
    draw.ellipse([100, 100, 200, 200], fill='yellow')  # Simple sun/moon
    draw.rectangle([50, 250, 250, 270], fill='green')  # Ground

print("🖼️ Displaying the artwork...")
display(starry_night)

print("🔮 AI is analyzing the artwork...")
result = captioner(starry_night)
description = result[0]['generated_text']

print("\n" + "="*60)
print("🌟 ESAG AI PROTOTYPE RESULTS")
print("="*60)
print(f"📝 AI DESCRIPTION: {description}")

# Create art-specific tags
words_to_remove = ['a', 'an', 'the', 'and', 'or', 'in', 'on', 'at', 'to', 'for', 'with', 'of', 'is']
tags = [word.strip('.,!?') for word in description.split() if word.lower() not in words_to_remove]

print(f"🏷️  AUTO-GENERATED TAGS: {', '.join(tags)}")
print("="*60)
print("✅ PROOF OF CONCEPT SUCCESSFUL!")
print("✅ This demonstrates automatic artwork tagging!")
print("✅ Buyers can search using these AI-generated tags!")

# ESAG AI ART TAGGING - ABSTRACT ART TEST
from transformers import pipeline
from PIL import Image
import requests
from io import BytesIO
from IPython.display import display

print("🎨 ESAG AI ANALYZING ABSTRACT ARTWORK...")
captioner = pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")

# Using a vibrant abstract painting
url = "https://images.pexels.com/photos/1585325/pexels-photo-1585325.jpeg?cs=srgb&dl=pexels-steve-1585325.jpg&fm=jpg"
response = requests.get(url)

if response.status_code == 200:
    abstract_art = Image.open(BytesIO(response.content))
    print("✅ Abstract artwork loaded successfully!")
else:
    # Create a colorful fallback abstract
    from PIL import ImageDraw
    abstract_art = Image.new('RGB', (300, 300), color='navy')
    draw = ImageDraw.Draw(abstract_art)
    # Add colorful shapes
    draw.rectangle([50, 50, 150, 150], fill='red')
    draw.ellipse([180, 80, 280, 180], fill='yellow')
    draw.polygon([100, 200, 200, 200, 150, 280], fill='green')
    print("🔄 Created colorful abstract artwork!")

print("🖼️ Displaying abstract artwork...")
display(abstract_art)

print("🔮 AI is analyzing the abstract painting...")
result = captioner(abstract_art)
description = result[0]['generated_text']

print("\n" + "="*60)
print("🌟 ESAG AI - ABSTRACT ART ANALYSIS")
print("="*60)
print(f"📝 AI DESCRIPTION: {description}")

# Create art-specific tags
words_to_remove = ['a', 'an', 'the', 'and', 'or', 'in', 'on', 'at', 'to', 'for', 'with', 'of', 'is']
tags = [word.strip('.,!?') for word in description.split() if word.lower() not in words_to_remove]

print(f"🏷️  AUTO-GENERATED TAGS: {', '.join(tags)}")
print("="*60)

# Show how this helps buyers
print("🎯 HOW THIS HELPS ART BUYERS:")
print("• Search for: 'colorful abstract painting'")
print("• Find art by mood: 'vibrant', 'energetic', 'modern'")
print("• Discover new artists through AI recommendations!")
print("="*60)
print("✅ AI understands both realistic AND abstract art!")
print("✅ Perfect for ESAG's diverse artist community!")